import path from "path";
import { readDoc, writeDoc } from "./persist";

const FILE = path.join(__dirname, "..", "..", "data", "profile.json");

/** The business this deployment writes for. Saved from the first-run setup screen. */
export interface BusinessProfile {
  businessName: string;
  whatYouSell: string;
  audience: string;
  location: string;
  tone: string;
  neverSay: string;
  brandVoice: string; // generated by Claude from the fields above (editable by the owner)
  market?: string; // market brief learned for this business (editable); appended to every prompt
  marketUpdatedAt?: string;
  updatedAt: string;
}

export function getProfile(): BusinessProfile | null {
  try {
    const raw = readDoc(FILE);
    const p = raw ? JSON.parse(raw) : null;
    return p && p.brandVoice ? (p as BusinessProfile) : null;
  } catch {
    return null;
  }
}

export function saveProfile(p: Omit<BusinessProfile, "updatedAt" | "marketUpdatedAt">): BusinessProfile {
  const prev = getProfile();
  const full = {
    ...p,
    updatedAt: new Date().toISOString(),
    marketUpdatedAt: p.market !== undefined && p.market !== prev?.market ? new Date().toISOString() : prev?.marketUpdatedAt,
  };
  writeDoc(FILE, JSON.stringify(full, null, 2));
  return full;
}
