import { AsyncLocalStorage } from "async_hooks";

/**
 * Which business ("tenant") the current request / job is working for.
 * The original single-business deployment is the "default" tenant: its documents keep their original
 * names, so existing data (ROCCA, Lugasi Gallery copies) keeps working untouched after the upgrade.
 * Every other tenant gets its own namespaced documents and never sees another tenant's data.
 */
export const DEFAULT_TENANT = "default";

const als = new AsyncLocalStorage<string>();

export const currentTenantId = (): string => als.getStore() || DEFAULT_TENANT;
export const isDefaultTenant = (): boolean => currentTenantId() === DEFAULT_TENANT;
export const runAsTenant = <T>(id: string, fn: () => T): T => als.run(id, fn);

/** Tenant ids are generated by the server (12 hex chars); anything else is refused so ids can never escape a path. */
export const isValidTenantId = (id: string): boolean => id === DEFAULT_TENANT || /^[a-f0-9]{12}$/.test(id);

let extraPlatforms: () => string[] = () => [];
/** Registered at start-up (avoids import cycles): platforms a non-default tenant has unlocked by connecting an account / having a site. */
export const registerExtraPlatforms = (fn: () => string[]): void => { extraPlatforms = fn; };

/**
 * Platforms a tenant may use. X and the operator's own website connector run on the OPERATOR's credentials, so only the default
 * tenant can use them. Every tenant publishes to its own Facebook/Instagram, and also to its own TikTok (once connected) and to its own BOOL website.
 */
export function allowedPlatforms<P extends string>(all: P[]): P[] {
  if (isDefaultTenant()) return all;
  const extra = extraPlatforms();
  return all.filter((p) => p === ("facebook" as P) || p === ("instagram" as P) || extra.includes(p));
}
